name: Main workflow
on:
  push:

jobs:
  test:
    runs-on: macos-latest
    timeout-minutes: 15
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Restore project
      run: |
        nuget restore SampleNunitProject.sln

    - name: Can i run nunit console runner?
      run: |
        find . -type d -maxdepth 5
        ls -la $GITHUB_WORKSPACE/packages
        ls -la $GITHUB_WORKSPACE/packages/NUnit.ConsoleRunner.3.12.0
        mono $GITHUB_WORKSPACE/packages/NUnit.ConsoleRunner.3.12.0/tools/nunit3-console.exe 