name: Main workflow
on:
  push:

jobs:
  test:
    runs-on: macos-latest
    timeout-minutes: 15
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Which mono do we have here
      run: |
        mono --version

    - name: Can i run nunit console runner?
      run: |
        mono $GITHUB_WORKSPACE/packages/NUnit.ConsoleRunner.3.12.0/tools/nunit3-console.exe 

